### ISSUE TITLE
Allow usage of URLs arguments in bodyFile

### ISSUE THREAD

**Issue by quentinfayet** [tejerka/mockserver#24]
Allowing the usage of in-URL defined arguments in the `bodyFile` property would allow to dynamically call different files. It would avoid the definition of a specific URL for each value of a variable part in a URL.

For example when mocking SearchConsole API :

```
-
  request:
    path: '/google/webmasters/v3/sites/:site/searchAnalytics/query'
    method: 'OPTIONS'
  response:
      headers:
        access-control-allow-credentials: 'true'
        access-control-allow-headers: 'authorization'
        access-control-allow-methods: 'GET'
        access-control-allow-origin: '*'
        access-control-max-age: '3600'
      bodyFile: './:site/query.json'
```

The format of the varibale in the `bodyFile` field still has to be defined.
